### ISSUE TITLE
Not working on ios

### ISSUE THREAD

**Issue by gbrigens** [0nza1101/firebaseCameraApp#1]
I have tried on ios device its not working.

1. I was getting this error `Internal navigation rejected: <allow-navigation not set> in Cordova on iOS` after researching online I got this a fix to place `<allow-navigation href="*" />` in `AppName/config.xml`.
 This time round I didn't get the error but it was not working the only thing am getting on debbuger in xcode is `CDVWKWebViewEngine: handleStopScroll` when I press upload on the device.

**Comment by 0nza1101** [comment]
Thanks for your feedback,
I have updated the repo, some of the firebase storage code where deprecated same for ionic camera part. You no longer need to set firebase storage and database rules. Tested and working on iOS. 
Closing the issue

**Comment by gbrigens** [comment]
I have tried am getting this error on launching "The given sign-in provider is disable for this Firebase project. Enable it in the Firebase console.." I have enable email and password... but still the same error also when I choose camera it take me to gallery and not camera. Is there anything I need to do before I run the app?

**Comment by 0nza1101** [comment]
You need to turn on anonymous login inside your Firebase console or replace : 
`firebase.auth().signInAnonymously()` from `src/pages/home/home.ts` to `firebase.auth().signInWithEmailAndPassword('newuser@mail.com', 'password')`.

For the camera issue its fixed.
